### ISSUE TITLE
plotting without padding cells

### ISSUE THREAD

**Issue by lheagy** [simpeg/discretize#10]
```
mesh.plotImage(sigma, padding=False)
```

would be very useful and help speed up a lot of the plotting code

**Comment by thast** [comment]
for the GPG labs (and now the DC apps) I have updated a (previously false) function of SimPEG that allows us to only plot the core mesh (useful for speed).
I did not merge it into SimPEG yet for 2 reasons:
-it only works for CC on 2D and 3D mesh (Faces and Edges are not implemented yet)
-GPG labs uses the master branch, and I was too short on time to risk a merge on master.

@lheagy, we can take advantage of the DC apps session friday to finish it and merge it into SimPEG

**Comment by lheagy** [comment]
closing this as we now have `range_x`, `range_y` in the plotting, and there isn't necessarily an obvious way to tell the difference between padding and not in many cases
