### ISSUE TITLE
Cylindrical anisotropy

### ISSUE THREAD

**Issue by rowanc1** [simpeg/discretize#12]
_From @rowanc1 on January 5, 2017 19:53_

As it is written now, the anisotropy is radial and in z. This is perhaps confusing, especially as theta is necessary but excluded from the tensor.

_Copied from original issue: simpeg/simpeg#529_

**Comment by lheagy** [comment]
Although it is potentially confusing, I don't think we should change this implementation (esp. now as we have a 3D cyl mesh). The input model for all cylindrical meshes (cyl symmetric and 3D cyl) should be the same.
