### ISSUE TITLE
numpy-styled docs

### ISSUE THREAD

**Issue by lheagy** [simpeg/discretize#126]
Similar to simpeg/simpeg#703, we should consider using numpy-styled docs for discretize. They are much cleaner to read inline, which is very relevant for when people pull up docs in Jupyter. 

https://numpydoc.readthedocs.io/en/latest/format.html

**Comment by leouieda** [comment]
I recently started using numpydoc for Fatiando and so far I quite like it. Makes it a lot easier to write the docstrings.

**Comment by grosenkj** [comment]
I like using the numpydoc format and support this move. It is much more legible in an interactive view, and in more logical to write. 
Does the auto-docstring generation in 'properties' work with numpydoc? If not, that should be easially implemented.

**Comment by jcapriot** [comment]
I agree, numpy styled docs are awesome! It's what I use in my own packages.

**Comment by lheagy** [comment]
@fwkoch: do you have any pointers on using numpy-styled docs with `properties`? In my first-pass implementation, there is a distinction in style between what is documented with properties and what is written in the code.

**Comment by prisae** [comment]
I'd be interested in this as well. As I subclassed `TensorMesh` I run into the same issue, in that the `properties`-declaration look out of place with `numpydoc`. Would simply using `@property` instead of `properties` be too much of a change/hassle?

**Comment by lheagy** [comment]
There is some conversation over in seequent/properties#251 on compatibility of properties with other doc-types
