### ISSUE TITLE
Organization of docs

### ISSUE THREAD

**Issue by lheagy** [simpeg/discretize#127]
# The problem

While looking at the style of the docs (#126), the organization should also be fleshed out. (we have part of the API documented in the "Tutorial"...)
![image](https://user-images.githubusercontent.com/6361812/49677586-64bab080-fa34-11e8-8323-2f4bf3818a6f.png). 

I am also debating if we want to try and separate the API docs from the User Documentation. In some ways, I think this might be good. We could describe the classes and provide a brief overview of its properties and methods and link each to the appropriate API page (this is approximately what numpy does). 

# A suggestion

I see the items in bold as headings in the table of contents side bar (see for example the [JOSS docs](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html))
**Overview**
- Why discretize?
- Getting started (which should be improved to include common windows problems) 
- Examples

**User Documentation**
- Finite volume (includes variable locations and terminology)
- Tensor Mesh
- Cylindrical Mesh
- Tree Mesh
- Curvilinear Mesh
- Differential Operators
- Inner Products
- Utilities
- Visualization
- VTK Module

**API**
- API

# Feedback?

I would appreciate thoughts here! (@leouieda, @prisae: you have both written beautiful docs - any suggestions here??)

**Comment by leouieda** [comment]
I really like this layout. That's what I've been using for Verde and it seems to work nicely. At least I find it a lot easier to find what I'm looking for. These are some examples of what I consider great docs:

* https://altair-viz.github.io/
* http://xarray.pydata.org/en/stable/
* http://docs.dask.org/en/latest/

**Comment by leouieda** [comment]
Copy away!

**Comment by lheagy** [comment]
Hi @leouieda: I have a question for you on using the `autosummary` / `automodule` whenever you have a minute. I have started working on this on the [repo-cleanup](https://github.com/simpeg/discretize/tree/repo-cleanup) branch. When documenting the API, I am having trouble getting sphinx to generate pages for classes inside of a submodule. For example in [api.rst](https://github.com/simpeg/discretize/blob/repo-cleanup/docs/api/index.rst), I have the summary building, and there are live links for all of the classes under "meshes" but no live links under "Base Mesh"

![image](https://user-images.githubusercontent.com/6361812/50865703-b15b1980-135b-11e9-8567-b81c0b27c36e.png)

Do you have any insights on what I might be missing? Thanks!

**Comment by lheagy** [comment]
Ah, I found it! I was missing the api build-step:

https://github.com/fatiando/verde/blob/dbf38867362e21a56c61072ce3cb905ea4cb340e/doc/Makefile#L33-L37

Thanks for creating such a clean makefile :)

**Comment by leouieda** [comment]
> Thanks for creating such a clean makefile :)

The default sphinx-generated Makefile always jarred me :)
