### ISSUE TITLE
organization of base classes

### ISSUE THREAD

**Issue by lheagy** [simpeg/discretize#128]
Users shouldn't really be using the BaseMesh, yet we are importing it in the `__init__.py`. I think we should remove this. Any concerns with this?

**Comment by lheagy** [comment]
With respect to organization, I quite like how @leouieda has put the base classes in a `base` directory in [verde](https://github.com/fatiando/verde/tree/master/verde). This is a lot more natural for documenting as I am discovering as I work on #127. I am inclined to follow and have
```
base/
    base_mesh.py  # BaseMesh and BaseRectangularMesh
    base_tensor_mesh.py  # BaseTensorMesh
``` 

thoughts?

**Comment by rowanc1** [comment]
I like! 👍
