### ISSUE TITLE
MyBinder pip install fails due to setup.py NumPy dependency

### ISSUE THREAD

**Issue by banesullivan** [simpeg/discretize#147]
Does anyone know of a way to get around the NumPy dependency for installing `discretize` in a fresh environment?

It would be really awesome to have the `discretize` example notebooks on [Binder](http://MyBinder.org)! Currently, Binder servers with `discretize` fail to build if `discretize` is in the `requirements.txt` because of the numpy dependency.

**Comment by banesullivan** [comment]
For launching on Binder: setting up a `requirements.txt` with numpy then a `postBuild` script with `python -m pip install discretize` appears to do the trick... not exactly elegant though.

Check out this Binder server demoing `discretize`: [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/OpenGeoVis/PVGeo-Examples/master)

**Comment by thast** [comment]
Hi @banesullivan,
I hope that helps in your case:
For [my own research repo binders,](https://github.com/simpeg-research/Astic-2019-PGI) following [@lheagy examples](https://github.com/simpeg-research/heagy-2018-AEM), I set up an [`environment.yml`, see link](https://github.com/simpeg-research/Astic-2019-PGI/blob/master/environment.yml)). I also depend on `discretize` and `numpy` and things run smoothly both on `MyBinder` and `Travis`.
You can also see the [ examples provided by `MyBInder`](https://mybinder.readthedocs.io/en/latest/sample_repos.html#conda-environment-with-environment-yml)
