### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by lheagy** [simpeg/discretize#149]
In #134, we restructured the docs and created a section that is a "User Guide" which is meant to be a collection of tutorials for getting users up and running with discretize. The format should follow the python files in the `docs/tutorials` directory. Below is a suggested outline. Please add your ideas / topics you would like to see!

- [x] Overview of mesh types 
- [x] Tensor meshes
- [x] Cylindrical meshes: how to create a 2D mesh, how to create a 3D mesh (see Tensor meshes for a template)
- [x] Tree meshes: how to create a QuadTree, how to create an OcTree, common methods of refining tree meshes
- [x] Finite volume introduction: where things are discretized, quick overview of differential operators
- [x] Divergence: derivation and overview of the FaceDiv operator on a 2D mesh
- [x] Curl: derivation and overview of the EdgeCurl operator on a 2D mesh, 3D mesh
- [x] Gradient: derivation and overview of the NodalGrad operator
- [x] Inner products: derivation and example of inner products
- [x] Solving the Poisson Equation: use discretize to solve a 2D DC resistivity problem
- [x] Boundary conditions
- [x] Visualization: examples that use the slicer and vtki

**Comment by lheagy** [comment]
cc @prisae, @dccowan: you have both expressed interest in docs. Your input would be much appreciated!

**Comment by prisae** [comment]
Looks like a solid outline. Definitely all the operators need some love, but I think you listed them all.

Another thing that might be explained better: `getInterpolationMat`. Along the same line, `Mesh2Mesh`, although that is in `SimPEG` and not in `discretize`, and similar features.

**Comment by jcapriot** [comment]
I think we've actually captured all of this detail!
