### ISSUE TITLE
Soft dependency for matplotlib

### ISSUE THREAD

**Issue by prisae** [simpeg/discretize#155]
At the moment `matplotlib` is a hard dependency (in the `setup.py`-file). Is there anything that speaks against making it a soft dependency just like `vtki`?

=> it is "only" used for the plotting of meshes, which is sort of a relatively small (but, agree, important) part of the whole `discretize` scope.
=> It would help to install discretize on minimal conda-environments for running models on a server, without having to install matplotlib.

**Comment by rowanc1** [comment]
Yeah, totally agree with that. Moving this into a soft dependency would be good.

**Comment by lheagy** [comment]
Completely agree!

**Comment by lheagy** [comment]
closed in #156
