### ISSUE TITLE
Broken Example: plot_3d_slicer

### ISSUE THREAD

**Issue by dccowan** [simpeg/discretize#158]
The example *plot_slicer_demo.py* breaks. This is related to *View.plot_3d_slicer*. In line 66 of the example, *fig = plt.gcf()*, we don't obtain an object with the axes from the previous plot. So *fig.get_children()* is empty.

Why aren't we using a *showIt* option and returning the figure like many of the other plotting tools?

**Comment by dccowan** [comment]
We should also control the figure size. Some of the text is overlapping and it looks messy.

**Comment by lheagy** [comment]
closed with #159. Feel free to re-open @dccowan if there are still issues here
