### ISSUE TITLE
to_vtk is too lenient with model array sizes

### ISSUE THREAD

**Issue by banesullivan** [simpeg/discretize#162]
@thast pointed out to me that there is an issue when passing non-vectorized data arrays to the `to_vtk()` method.

```py
import pyvista as pv
import numpy as np
import discretize

mesh = discretize.TensorMesh.readUBC('Mesh_model/mesh3d.msh')

model3d = np.load('Mesh_model/model.npy')
print(model3d.shape, model3d.size)
```
((10000, 28), 280000)

Then this:

```py
mesh.to_vtk({'model3d': model3d})
```

works fine but as soon as you try to use that PyVista mesh, the VTK backend will segfault.

The reason you are able to create the PyVista object has to do with this check:

https://github.com/simpeg/discretize/blob/c16e34c93fd0b0b2848751ddde5cccbaadb5b82f/discretize/mixins/vtkModule.py#L88-L89

Should we change this to check the first axes of the model array? This way users could pass arrays containing vector data (`nc` by 3):

```py
...
if mod.shape[0] != nc: 
     raise RuntimeError(...
```

**Comment by banesullivan** [comment]
I'd like the SimPEG community's feedback on this as there seems to be a lot of different ways users here handle model arrays - specifically regarding their shapes and orders ('C' vs 'F')

**Comment by thast** [comment]
Thanks @banesullivan.

I think changing the test from `size` to `shape` is a good idea.

My issue when not vectorizing the model was that it did not throw me an error. Later, trying to use the `pyvista` object, I still did not get an error but my whole `Python` kernel died. This can be annoying if your script is long to run, and you do not know what went wrong. Getting an error earlier, without killing the whole kernel, would be very beneficial.

In most cases in SimPEG, we use `order='F'`. Non vectorized model are  not common. In this case, it was just me making a silly oversight, while interpolating from multiple 1D mesh to a global 3D mesh.

**Comment by banesullivan** [comment]
Would a model array ever not be a NumPy array / have a `.shape` attribute?

Are lists ever used?

**Comment by thast** [comment]
No, we are using them in a lot of Linear Algebra so it has to be a 1D numpy array. I think we always assume a 1D vector, even when we have several physical properties at hand (we would then just stack them).

**Comment by banesullivan** [comment]
Okay awesome! Then I think #163 is an appropriate fix for this issue and it should prevent kernel crashes.
