### ISSUE TITLE
Numpy 1.15 with discretize?

### ISSUE THREAD

**Issue by orerocks** [simpeg/discretize#164]
The Geosoft API currently has a bug that is incompatible with numpy=1.16 (similar to the recent [writetable error in PyTables](https://github.com/PyTables/PyTables/issues/719)). I am running an environment (with a YAML config) that sets numpy<1.16. It works great, until I install discretize. If I install straight from pip it throws a compile error at runtime. If I force recompiling then it helpfully replaces numpy 1.15 with numpy 1.16 and breaks the Geosoft API, but allows discretize to work ok.

Is there a way to keep numpy=1.15 with discretize?

**Comment by thast** [comment]
@fourndo  mentioned that the other day (for `geotoolskit`)! 

I am not aware of any problem using `discretize` with `numpy=1.15` (else we need to change our requirements, which only specify `numpy>1.8` at the moment)

Once `discretize` is installed, try the command line:
`pip install numpy==1.15.4 --upgrade --force-reinstall`

Let us know if you experience issue running `discretize` with `numpy=1.15`. If you encounter it again,  send us a screenshot of the compiling error at runtime you got.

**Comment by orerocks** [comment]
With a fresh conda environment with numpy==1.15.4 and discretize installed directly from the YAML environment file I get the following error:
![2019-05-15 21 34 08](https://user-images.githubusercontent.com/31866231/57826815-b987f300-7759-11e9-9575-13d3f8e45609.png)

If I recompile discretize `pip install --upgrade --force-reinstall discretize` discretize works, but numpy gets upgraded and Geosoft breaks.

If I try to force a numpy rollback with `conda install numpy==1.15.4 --force-reinstall` it does things, but leaves numpy at 1.16 (presumably because numpy 1.16 was installed via pip in the discretize compile, and not by conda). 

If I instead force a numpy rollback with `pip install numpy==1.15.4 --upgrade --force-reinstall` it goes back to the original `numpy.ufunc size changed error`. Future package updates in conda also then report:
```
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:
```
and list most of the installed packages.

This is obviously a problem with Geosoft, not discretize, but just trying to get things done while they get around to fixing it.

**Comment by thast** [comment]
Hum, I think if this is due to the pre-compiled `wheel` file on `PyPi`, that likely were done with `numpy=1.16`.
I am able to run `discretize` and `numpy=1.15.4`, but I run `discretize` from a cloned version on my machine and not from `pip`...  

Only thing I can think of right now is, once you have `discretize` and `numpy=1.15.4`, to follow this [stackoverflow post  and](https://stackoverflow.com/questions/40845304/runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility) add in your script:
`import warnings`
`warnings.filterwarnings("ignore", message="numpy.dtype size changed")`
`warnings.filterwarnings("ignore", message="numpy.ufunc size changed")`

**Comment by orerocks** [comment]
Thanks for the clue @thast.

The warning ignore doesn't help, it just throws a different error when importing Simpeg:
![2019-05-16 08 19 27](https://user-images.githubusercontent.com/31866231/57866865-e9b0af80-77b4-11e9-9572-bb56bf4971e7.png)

But clicking through those SO entries I found [a solution here](https://stackoverflow.com/questions/25752444/scipy-error-numpy-dtype-size-changed-may-indicate-binary-incompatibility-and).
```
pip uninstall -y discretize
pip install --no-binary :all: discretize
```

That seemed to recompile with the existing installation, giving me the earth, moon, and stars: numpy==1.15.4 **and** discretize **and** geosoft

**Comment by lheagy** [comment]
Glad you were able to fight through this @orerocks. Nice work!

**Comment by rowanc1** [comment]
Also related to https://github.com/GeosoftInc/gxpy/issues/116.
