### ISSUE TITLE
Boundary Conditions for all mesh types

### ISSUE THREAD

**Issue by dccowan** [simpeg/discretize#170]
It seems like we can only invoke general boundary conditions on tensor meshes. This should be done for all mesh types. We should be able to impose Dirichlet, Neumann and mixed conditions on operators for Tree and Cyl meshes as well.

**Comment by lheagy** [comment]
Thanks for raising this @dccowan! There is some related discussion from way back here: #20

**Comment by jcapriot** [comment]
Closing this for the same reasons as #20
