### ISSUE TITLE
Colorbar functionality mesh.plotImage not working for OcTree mesh

### ISSUE THREAD

**Issue by lheagy** [simpeg/discretize#173]
Transferred from simpeg/simpeg#782 by @sarahgarre

---

Hi, I have to change the default colorbar used by mesh.plotImage to prevent images from being counterintuitive for my application. However, the cb='colorbar_name' option does not seem to have any effect. Is this a bug or am I doing something wrong?

`out = my_mesh.plotImage(sigma_wrong,clim=[0,6],ax=ax1,cb='jet') 

--- 

@fourndo I think you already identified the problem, no? The TreeMesh plotImage function does not have the dictionary for colorOpts. Is it possible to fix this somewhere soon?

---

**Comment by jcapriot** [comment]
The plotImage functions do not take this as an option in that manner. Instead use the `pcolorOpts` kwarg. And pass it a dictionary that defines a ‘cmap’.

I.e. `pcolorArgs={‘cmap’:’jet’}`

**Comment by thast** [comment]
@jcapriot : I think that is what she meant. We tried with `pcolorOpts` but it seems the argument is missing from the `TreeMesh.plotImage` function (see screenshot below):
![image](https://user-images.githubusercontent.com/13682747/58500269-abad7700-8136-11e9-9e97-436deea5c51e.png)

**Comment by jcapriot** [comment]
That screenshot is from an older version of discretize. The relevant line changed in 0.4.1.

https://github.com/simpeg/discretize/blob/75f50681c3c58b4b1e1c647d6664492ba0aee2b3/discretize/tree_ext.pyx#L3022

In push https://github.com/simpeg/discretize/commit/384397f8c3b36d31f9bd147950c97cf36223a608

**Comment by thast** [comment]
Thanks @jcapriot ! We will update and check again.

**Comment by sarahgarre** [comment]
ok, after updating discretize independently from SimPEG and restarting my Jupyter kernel, I managed to change the colorbar using `pcolorOpts={'cmap':'hsv'}`
