### ISSUE TITLE
Document features inherited from properties.HasProperties

### ISSUE THREAD

**Issue by banesullivan** [simpeg/discretize#176]
Is there a method to compare two meshes to see if they are the same; i.e. have the same discretization? 

If not, perhaps it would be useful to implement a `.equals()` method for each mesh type to compare other meshes and return `True`/`False`

**Comment by banesullivan** [comment]
Actually, I'm realizing now the `discretize` inherits the `.equal()` method from the `properties.HasProperties` class

🤦‍♂ 

Perhaps this should be documented along with other nifty things inherited from `properties`

**Comment by jcapriot** [comment]
Closing this, as `discretize` no longer depends on `properties`
