### ISSUE TITLE
Metaclass conflict when importing discretize

### ISSUE THREAD

**Issue by ismacaulay** [simpeg/discretize#184]
**What was done**
1. Using a new python 3.7.3 virtualenv, run `pip install discretize`
2. Start the python interpreter
3. run `import discretize`

**What was seen**
```
>>> import discretize
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ianmacaulay/tmp/venv3/lib/python3.7/site-packages/discretize/__init__.py", line 2, in <module>
    from discretize.TensorMesh import TensorMesh
  File "/Users/ianmacaulay/tmp/venv3/lib/python3.7/site-packages/discretize/TensorMesh.py", line 15, in <module>
    InnerProducts, TensorMeshIO
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**What was expected**
Discretize should import properly.

OS: MacOS 10.14.6
python: 3.7.3
Version: 0.4.9

The only version that I was able to get to work was 0.4.4 on a clean install, although I was required to install numpy myself before I could install discretize

**Comment by prisae** [comment]
Can you do a `pip install scooby` and then in your Python environment a
```
import scooby
scooby.Report(['discretize', 'SimPEG'])
```
and post the output?

**Comment by ismacaulay** [comment]
It fails to load it as well
![image](https://user-images.githubusercontent.com/1445333/62964903-2a729180-bdc1-11e9-8768-71ab776c39cb.png)

Heres what it looks like using **0.4.4** (incase any of the information is helpful)
![image](https://user-images.githubusercontent.com/1445333/62965025-61e13e00-bdc1-11e9-9d55-ceda2b2b482f.png)

**Comment by banesullivan** [comment]
Does this issue remain when using a more recent version of `discretize`? `0.4.4` is outdated (but not that old)

```bash
pip install -U discretize
```

**Comment by ismacaulay** [comment]
`0.4.4` is the last version that I can get to work. `0.4.5` and newer all seem to have the same issue

**Comment by prisae** [comment]
Do `pip install matplotlib`, and it should work. I suspect it has to do with the soft import of `matplotlib`, something must be broken there.

**Comment by prisae** [comment]
I can not dig into it deeper right now, but I'll have a look later this week.

**Comment by prisae** [comment]
One issue is TreeMesh.py - it has `matplotlib`-imports in the middle of the file instead of on top of the file, which I unfortunately missed in the original PR.

**Comment by jcapriot** [comment]
those are imported when the function is called

**Comment by prisae** [comment]
Yes, it is not actually the problem here. However, the import should be moved to the top here also, and made optional, as in the other files, and then decorate the actual plotting function with a `@requires`-decorator.

However, more important is first to find out what causes it to fail if matplotlib is not installed, this `TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases`-error.

**Comment by jcapriot** [comment]
Did you trace the bug to the matplotlib import? I don't see any other mention of it in this bug report.

**Comment by prisae** [comment]
Sort of. I could reproduce the behaviour reported by @ismacaulay, and installing matplotlib resolved it. Furthermore, 0.4.4 is the last version he could install, and 0.4.5 was my introduction of matplotlib as a soft dependency, so I must somehow have screwed up. I wonder why the tests did not catch it, I am pretty positive that I tested it without matplotlib installed back then, and there were no issues.

@ismacaulay, did it work for you?

**Comment by prisae** [comment]
Let us know if it works for you with discretize v0.4.10, @ismacaulay !

**Comment by ismacaulay** [comment]
@prisae 0.4.10 works fine for me now. Installing `matplotlib` in `0.4.9` also fixed it. Thanks for getting this resolved so quickly

**Comment by prisae** [comment]
Great to hear! And I am glad I could fix it, as I am the one to blame for introducing the bug, as I wanted the matplotlib dependency to become a soft dependency.
