### ISSUE TITLE
Python 3.5 Support???

### ISSUE THREAD

**Issue by banesullivan** [simpeg/discretize#219]
The docs imply `discretize` still supports Python 3.5 (see [this](http://discretize.simpeg.xyz/en/master/content/installing.html#which-python)) yet there are f-strings (F-strings were introduced in Python 3.6) in:

https://github.com/simpeg/discretize/blob/a4ead91d6a1f84658ab20946da5fa86dc9ccc831/discretize/MeshIO.py#L479-L482

I see there are no CI tests for Python 3.5

**Comment by banesullivan** [comment]
Which yields a syntax error on import:

```
    import discretize
805  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/discretize/__init__.py", line 2, in <module>
806    from discretize.TensorMesh import TensorMesh
807  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/discretize/TensorMesh.py", line 10, in <module>
808    from .MeshIO import TensorMeshIO
809  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/discretize/MeshIO.py", line 479
810    head = ' '.join([f"{int(n)}" for n in nCunderMesh])+" \n"
811                               ^
812SyntaxError: invalid syntax
```

**Comment by banesullivan** [comment]
There should be a `python_requires` setting in the `setup.py` to prevent people from installing incompatible versions of discretize like this.

**Comment by lheagy** [comment]
:+1: good catch @banesullivan

**Comment by banesullivan** [comment]
Is there a consensus on how to proceed with this? It's blocking me on a side project and I may have time to fix the broken 3.5 code and set up the CI testing on Python 3.5 (all supported versions)

cc @jcapriot

**Comment by prisae** [comment]
Do you need Python 3.5 for discretize, @banesullivan ? My goto would have been to add `python_requires>=3.6` to `setup.py`, as Python 3.5 EOL is in two weeks. But if someone still needs it... No one commented on Slack about @lheagy inquiry in this regard.

**Comment by banesullivan** [comment]
I'm down for dropping 3.5 support ... after that though I think discretize's CIs should test all versions of python >3.5 as quite a number of other libraries have it as a dependency these days.

It may be good to hard set what versions of python are compatible.. e.g >3.5,<3.9 to prevent something like this from happening again

**Comment by jcapriot** [comment]
Hey @banesullivan, I'm certainly in favor of dropping 3.5 support at this point, and also agree that the CI should be done on all current python versions, I've been working on getting this all setup using azure pipelines and that engine, which will allow us to have a centralized testing of the package on all OS's and all versions. It's also slightly faster than travis's images.
