### ISSUE TITLE
Interpolation

### ISSUE THREAD

**Issue by rowanc1** [simpeg/discretize#23]
_From @rowanc1 on November 17, 2015 22:0_

In the interp utils we should be using `np.searchsorted` rather than `np.argmin` over the vectors:

Speed up of O(log(n)) vs O(n) for each point you are interpolating, could be significant, especially on large meshes.

_Copied from original issue: simpeg/simpeg#170_

**Comment by jcapriot** [comment]
I think we could actually get away without having the interputil_cython extension if you used `np.searchsorted` as that function accepts a list of points to insert.
