### ISSUE TITLE
Release notes also on GitHub

### ISSUE THREAD

**Issue by prisae** [simpeg/discretize#230]
I would advocate for / appreciate if we can copy the release notes to GitHub as well.

I think GitHub is often the first place you look, very often before the docs. At the moment that is misleading:

![Selection_002](https://user-images.githubusercontent.com/8020943/99515668-8a28f680-298d-11eb-9ab5-e8692362e93c.png)
![Selection_001](https://user-images.githubusercontent.com/8020943/99515672-8bf2ba00-298d-11eb-9a82-d578f22e554a.png)

Maybe not for point releases, but at least for major/minor releases. What do you think? I thought today for quite a while that the PR's were pushed to master, but are not released yet...

**Comment by jcapriot** [comment]
Patience sir!

**Comment by prisae** [comment]
Sorry @jcapriot ! It just caught my eye today, so I thought I'd ask if it is the plan or not.
