### ISSUE TITLE
Null Space of curl curl operation

### ISSUE THREAD

**Issue by rowanc1** [simpeg/discretize#24]
_From @rowanc1 on November 4, 2015 18:49_

_From @lheagy on June 29, 2015 21:24_

When frequency is small, there is a null space that can cause issues. It can be corrected by enforcing conditions on the divergence of the field and or flux at play (not that if solving the 2D cyl mesh problem for h or e, this isn't an issue)

_Copied from original issue: simpeg/simpegem#25_

_Copied from original issue: simpeg/simpeg#149_

**Comment by lheagy** [comment]
This is something that should be addressed over in SimPEG if we encounter issues. So far it hasn't been a problem, so I will close this for now.
