### ISSUE TITLE
Pip installer fails on Windows

### ISSUE THREAD

**Issue by domfournier** [simpeg/discretize#243]
Installing discretize from pip returns this error on windows:
![image](https://user-images.githubusercontent.com/55204635/115275408-9d83ed80-a0f6-11eb-8d94-45c256c2c030.png)

**Comment by jcapriot** [comment]
Try updating numpy to >1.20.

**Comment by Furlan63** [comment]
Did you ever find a solution to this problem? I'm currently having the same issue trying to install on a new computer.

**Comment by jcapriot** [comment]
This error implies a binary incompatibility between numpy and discretize, which likely means that pre-built wheels provided for windows on pypi are compiled against a version of numpy that is newer than the one you currently have in your environment.

If you do not want to use conda-forge to install discretize then, as indicated above, try updating your numpy installation, or installing from source.

**Comment by jcapriot** [comment]
Assuming that solution worked, closing this issue
