### ISSUE TITLE
Potential updates for `electromagnetics.frequency_domain`

### ISSUE THREAD

**Issue by sgkang** [simpeg/discretize#245]
These are thoughts that I had while integrating `emg3d` into `SimPEG`

- [ ] General direction for receiver objects (currently it only supports x, y, z)
- [ ] Line source implementation (I worked on this with @micmitch and @jcapriot, so we should bring that in) / the same implementation can be used for receivers. 
- [ ] Handling of complex data (currently, we assume the data are real-valued); this could save some time. 
- [ ] When addressing an adjoint operation, we use transpose, but this is needed to be Hermition (it works, but might be better to make change...)

**Comment by jcapriot** [comment]
I believe this was incorrectly posted to `discretize` instead of `SimPEG`.
