### ISSUE TITLE
Discretize won't install (Command errored out with exit status 1)

### ISSUE THREAD

**Issue by FilipArnaut** [simpeg/discretize#259]
Help needed with discretize. 

Both with Simpeg and installing it individually via pip will not work and will send out an  "Command errored out with exit status 1"  (same as other people had). How can I solve it?

Pip version 21.2.3
Numpy version 1.21.1
Python 3.9.4

Thank you in advance.

**Comment by jcapriot** [comment]
Can you give us more details?

What OS are you on?
What was the full error message?

In general we recommend installing discretize through conda-forge. As it is the simplest means of distributing the compiled code. However there are discretize wheels for windows on pypi that come pre-compiled, but I’ll have to check if it’s currently being built for 3.9

**Comment by FilipArnaut** [comment]
Yes, I forgot about more details.

I'm on Windows (10.0.19043).

And here is the full error that I get attached below as a .txt file (too long to screenshot).

[Discretize_Install_Error.txt](https://github.com/simpeg/discretize/files/6951206/Discretize_Install_Error.txt)

Maybe I should downgrade to Python 3.8.x, do you think that will solve the problem?

**Comment by FilipArnaut** [comment]
For anyone that might encounter the same problem in the future,

I have managed to solve the problem by downgrading from python 3.9.4 to python 3.8.6, now I had no trouble installing discretize via the pip install command.
