### ISSUE TITLE
Wheels for Windows

### ISSUE THREAD

**Issue by rowanc1** [simpeg/discretize#26]
Should consider building wheels for distribution without compilation.

@jcapriot do you have any idea how to do this? I think that we can create a wheel on appveyor, I will give it a first shot.

http://wheel.readthedocs.io/en/latest/
https://packaging.python.org/appveyor/

**Comment by rowanc1** [comment]
See 400586c405e23f6923a9833e47404c11ddbde4b4.

**Comment by rowanc1** [comment]
They are getting built, and saved. We may want 64bit? As well as python 2.7.

https://ci.appveyor.com/project/lheagy/discretize/build/1.0.50/artifacts

I will aim to upload these on the next release.

**Comment by jcapriot** [comment]
32, and 64 both seem like good ideas, as well as 2.7 and 3.5.
The good thing about this is that we can package up the main simpeg branch as a universal python wheel (works on 2 and 3, and is pure python). So a single wheel file can be used to distribute all of the simpeg code.

**Comment by jcapriot** [comment]
http://refi64.com/posts/using-appveyor-to-distribute-python-wheels.html

**Comment by lheagy** [comment]
For distributing, does this mean we should do the entire pypi upload from appveyor? or can we upload to pypi from travis and then attach the wheels?

**Comment by lheagy** [comment]
This looks like it might be what we need: https://pypi.python.org/pypi/appveyor-artifacts/1.0.2

**Comment by lheagy** [comment]
Windows is still touchy and often Visual C++ issues arise. Perhaps we don't import TreeMesh stuff by default?? 

cc @fourndo, @rowanc1
