### ISSUE TITLE
CylMesh Theta Discretization

### ISSUE THREAD

**Issue by rowanc1** [simpeg/discretize#27]
I think @lheagy has already started on the theta discretization, which is needed for some more accurate wire paths in a casing example.

Later down the road, could be interesting to do both `r[0]>0` or `\theta \in [0, 1.5]`?

![image](https://cloud.githubusercontent.com/assets/913249/22615795/f640b69a-ea59-11e6-87e7-ca320b5f47e0.png)

![image](https://cloud.githubusercontent.com/assets/913249/22615797/025acbf0-ea5a-11e6-9254-d9822285c173.png)

**Comment by lheagy** [comment]
This will be addressed in #36

**Comment by lheagy** [comment]
This closed with #36
