### ISSUE TITLE
setuptools? 

### ISSUE THREAD

**Issue by lheagy** [simpeg/discretize#274]
I recently had some issues with conda so deleted that directory and am working through re-installing things. I tried re-installing discretize in-place but ran into the following error:

```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      error: Multiple top-level packages discovered in a flat-layout: ['gallery', 'tutorials', 'discretize', 'credentials', 'laguna_del_maule_slicer'].
```

(This same failure occurs in geoana and simpeg, but I figured I would start here.) So I think we are perhaps behind on where setuptools wants us to be?

**Comment by jcapriot** [comment]
I did notice that this was causing build errors on discretize here as well. The switchover to the most recent main should've fixed those issues though, as it explicitly includes discretize as a package, and doesn't use a general thing. Can you test this on main?

**Comment by lheagy** [comment]
thanks @jcapriot, I pulled the latest main and now it is okay :)
