### ISSUE TITLE
Bug in recent changes to v0.8.0

### ISSUE THREAD

**Issue by benk-mira** [simpeg/discretize#279]
Ran into the following bug today:

![image](https://user-images.githubusercontent.com/81254271/168397985-e384f48b-c4e1-4fc9-a170-db052acaf1ff.png)

Think it might be due to some recent changes to v0.8.0.  I downgraded to v0.7.4 and the bug is gone

**Comment by jcapriot** [comment]
SimPEG should be updated there. The _REGISTRY property was being needlessly imported there, and was a carryover from when properties was a part of this package.
