### ISSUE TITLE
Inconsistency in `read_UBC` method definition and its docstring

### ISSUE THREAD

**Issue by santisoler** [simpeg/discretize#290]
There's an inconsistency between the parameters listed on the `TreeMeshIO.read_UBC` method and its docstring. The `meshFile` parameter should be replaced with `file_name` (or the other way around, depending which is preferred).

https://github.com/simpeg/discretize/blob/8c59bebb9bef17e508ce2055509968ee6142d935/discretize/mixins/mesh_io.py#L436-L483

On a side note, I noticed that there is a `TreeMeshIO.read_model_UBC` method that is supposed to perform a very similar task, but it's not decorated as a `classmethod` and its docstring are also inconsistent with the method definition. Is there a reason for both to exist? If so, I think it would be better to rename any of them to make their differences more explicit.

**Comment by jcapriot** [comment]
For the `read_UBC` method, it is just a matter of a variable name change there, in which case it should be changed `file_name`.

The `read_model_UBC` should not be a `classmethod`

**Comment by jcapriot** [comment]
Believe this inconsistency is now corrected.
