### ISSUE TITLE
Use std::unordered_map in tree.h

### ISSUE THREAD

**Issue by domfournier** [simpeg/discretize#303]
https://github.com/simpeg/discretize/blob/90f8482d22c486563af0218508fe82cf23d9820d/discretize/_extensions/tree.h#L5

 Recommendation from K Davis.
Using unordered should speed up the creation

**Comment by jcapriot** [comment]
So got a chance to chat with him at PDAC, unordered maps would speed up creation, however we would loose any guarantee of ordering of nodes, edges, and faces from one call to the next.

Right now the ordering of faces is guaranteed to be in certain order (although it is not necessarily obvious to the user). Thus, if you saved a mesh to disk, read it back in, those faces would be in the same order as they were before. The unordered map would not be able to guarantee this property, which means we are likely stuck with the normal standard map.
