### ISSUE TITLE
Installing from pypi

### ISSUE THREAD

**Issue by lheagy** [simpeg/discretize#32]
Currently, from pypi, the `build_ext --inplace` is not being run, so efficiency warnings are thrown. 

For example, when testing SimPEG https://travis-ci.org/simpeg/simpeg/jobs/201040464 

![image](https://cloud.githubusercontent.com/assets/6361812/22893057/7a622906-f1c9-11e6-8a7a-756a1d2eb95e.png)

**Comment by jcapriot** [comment]
I think all references to this error (and suggested fix) should be removed. It is actually an import error, and running that command will certainly not fix it (It only would have fixed it if running python from the base simpeg directory). It is almost always another issue that having this message hides. In general, the discretize package must be installed, which it looks from the logs like it was successfully.

**Comment by jcapriot** [comment]
I think this error is being thrown from the main SimPEG branch. I think some of the things in `SimPEG.Utils` should be imported from this package instead of leaving them in there.

**Comment by lheagy** [comment]
ah, that is quite likely. Utils need a bit of an over-haul :)
