### ISSUE TITLE
Separating operator stencils and geometry

### ISSUE THREAD

**Issue by lheagy** [simpeg/discretize#42]
Right now, there is a mix of the existence of `Stencil` operators, which contain the core of the operator, but not the length scales associated with a specific mesh, and those that don't. 

The stencil is specific to the mesh type, but the way we incorporate sizes (and do deflation) is general and could be abstracted. This would clarify what pieces need to be implemented when designing a new mesh and which can be inherited. Also, components can (and should!) be broken up so that when calculating the `Div` for example, it just grabs the x, y, z div pieces (this means they can then be tested and used independently. 

This would require a bit of re-organization, but should make it more clear which code needs to live with each specific mesh, and what comes from `DiffOperators`

cc. @rowanc1

**Comment by jcapriot** [comment]
This is implemented currently for all of the regular structured meshes. We could also do the Unstructured meshes as well but those do not necessarily separate as nicely (specially for the x-y-z pieces of the derivatives). If we need the nodal gradient stencil, face divergence stencil, and edge curl stencil for the other mesh types then we can open specific issues for those.
