### ISSUE TITLE
inner product names

### ISSUE THREAD

**Issue by lheagy** [simpeg/discretize#43]
- `getEdgeInnerProduct` --> `edgeInnerProduct`
- `getFaceInnerProduct` --> `faceInnerProduct`

thoughts @rowanc1 ?

**Comment by rowanc1** [comment]
That sounds fine.

I would like to deal with this in a PEP8 blitz as well. #39. So `_`s are probably better.

**Comment by leouieda** [comment]
Do they take any input arguments? If not, converting them to `@property` would be nice to get rid of the `()`

**Comment by rowanc1** [comment]
These ones do take inputs, yes, they are dependent on the physical property:

```python
MeSigma = mesh.getEdgeInnerProduct(sigma, invertMatrix=True)
```

**Comment by leouieda** [comment]
Right, that makes sense.

**Comment by jcapriot** [comment]
handled in the pep8 rename a while ago
