### ISSUE TITLE
Octree model sections

### ISSUE THREAD

**Issue by lheagy** [simpeg/discretize#45]
Originally from @micmitch in simpeg/simpeg#575 

I have set up a small problem for testing the regularization operators on an octree mesh using a DC problem. This small problem (~50,000 cells) inverts in about 10 min but it takes almost as long for it to generate a 3 panel plot of model sections. I'm assuming this has something to do with interpolation. Any thoughts on how we could potentially speed this up?

**Comment by rowanc1** [comment]
Oh man. That is ridiculous. I think that it uses the plot2d code from the tensormesh to do the plotting. I don't know off hand why it would be so slow. Can you provide your mesh that you are using?

**Comment by micmitch** [comment]
Here is a link to a folder with my plotting notebook and required mesh and model files.

**Comment by micmitch** [comment]
https://www.dropbox.com/sh/7zilmw6k0s2ilz2/AAAOzGFz5B2oBMngp3ntd-Hka?dl=0

**Comment by jcapriot** [comment]
This now appears to take about a second to plot these images on my personal computer.

**Comment by micmitch** [comment]
That's awesome! Thanks @jcapriot!
