### ISSUE TITLE
getEdgeInnerProduct invMat = True needs to be implemented

### ISSUE THREAD

**Issue by lheagy** [simpeg/discretize#52]
*originally from* simpeg/simpeg#105

Should be able to call: (for diagonal models, it is simple, for fully anisotropic, it involves a matrix solve) 
self.mesh.getEdgeInnerProductDeriv(self.curModel.sigma, invMat=True)(u)
self.mesh.getFaceInnerProductDeriv(self.curModel.mui, invMat=True)(u)

**Comment by jcapriot** [comment]
We do support invert_matrix=True for diagonally anisotropic models on axis-aligned meshes as these mass matrices are diagonal, however anything higher than this does indeed require a general matrix solve, which someone might not expect to happen and cause a large memory requirement. I think it's safer to rely on the user to use their own matrix solver if needed for these cases.
