### ISSUE TITLE
utils.spzeros efficiency

### ISSUE THREAD

**Issue by lheagy** [simpeg/discretize#60]
I think we want to use `sp.dia_matrix` instead of `sp.csr_matrix` for `utils.spzeros` (2x speedup) 

![image](https://user-images.githubusercontent.com/6361812/27048362-4e962472-4f60-11e7-8aa0-ad0036027167.png)

**Comment by lheagy** [comment]
and if the matrix isn't square, it is still faster
![image](https://user-images.githubusercontent.com/6361812/27049479-599b8f0c-4f64-11e7-93ee-42db93d9f2a4.png)

**Comment by jcapriot** [comment]
That makes a lot of sense, considering how the csc/csr matrices are stored, an empty diagonal matrix doesn't require any storage space, whereas the csc/csr matrices still require offset storage which is just an array of zeros the length of columns/rows.

**Comment by lheagy** [comment]
closed with #61
