### ISSUE TITLE
Tab completion on TreeMesh objects

### ISSUE THREAD

**Issue by micmitch** [simpeg/discretize#65]
After creating a new TreeMesh object tab completion on other objects/packages works. 

Trying to tab complete on the mesh object however, produces no results and breaks any further attempts to tab complete on other objects or packages. 

Below is a simple example which shows this.

<img width="1141" alt="screen shot 2017-06-27 at 1 32 40 pm" src="https://user-images.githubusercontent.com/13682778/27608673-2553c6e4-5b3d-11e7-8dc4-7452ec85309b.png">

Here is the mesh file if you would like to try reproducing the problem.

[SingleBlk5m_Top_3mFromTunnel_Octree_Core14_10_6_1kmPad_Reg.txt](https://github.com/simpeg/discretize/files/1106666/SingleBlk5m_Top_3mFromTunnel_Octree_Core14_10_6_1kmPad_Reg.txt)

**Comment by rowanc1** [comment]
That seems super strange. Is the mesh valid? did it actually get created?

**Comment by micmitch** [comment]
Yep. Pretty sure that the mesh object is in good shape. Have not had any problems doing the forward modelling with it.

**Comment by jcapriot** [comment]
I haven't had any issues with this in the new version, if Anyone else does, please re-open the issue.
