### ISSUE TITLE
Tree Mesh on Windows

### ISSUE THREAD

**Issue by rowanc1** [simpeg/discretize#7]
This currently does not work. If someone is interested in helping, it has something to do with long integers that are not represented well in c?

The cython is doing some bitshifting which windows does not like... :(

**Comment by jcapriot** [comment]
Now that you mention this, I remember fixing this on my install on the windows PC a while back...
change the `long` to `long long`, as `long` and `int` are usually the same.

**Comment by rowanc1** [comment]
#9 has fixed this!
