### ISSUE TITLE
Include method gridH to mesh typcs Tensor and Tree

### ISSUE THREAD

**Issue by dccowan** [simpeg/discretize#74]
For the code I am writing, I would like to have a method mesh.gridH which behaves like mesh.gridCC. The method would output the cell dimensions of all cells into an array of dimension NX3.  I know that from the mesh properties, this can be computed fairly easily. Nevertheless, it would come in handy and avoid cluttering up space in my Problem class.

**Comment by lheagy** [comment]
`mesh.h` achieves this (or if you would like each component independently, `mesh.hx`, `mesh.hy`, `mesh.hz`

![image](https://user-images.githubusercontent.com/6361812/31012854-b545177e-a513-11e7-8f4c-c08e379ac872.png)

**Comment by dccowan** [comment]
I have written this function and there is now an active pull request
