### ISSUE TITLE
Devin Cowan (@dccowan) permission to push branch to discretize

### ISSUE THREAD

**Issue by dccowan** [simpeg/discretize#75]
I am contributing towards SimPEG and discretize. I require some permissions.

**Comment by lheagy** [comment]
hi @dccowan: we are happy to add you to the SimPEG organization. You should have received an invite from github. If you accept it, you will be able to push to the repository. Please have a look at the practices page of the documentation for a few pointers on contributing: http://docs.simpeg.xyz/content/api_core/api_practices.html
