### ISSUE TITLE
Discretize and Properties on Windows Machine

### ISSUE THREAD

**Issue by thast** [simpeg/discretize#76]
Devi and I are getting the same issue on our Windows machine:
![discretize_properties](https://user-images.githubusercontent.com/13682747/30985096-17e38f94-a444-11e7-8701-e0775cc60546.png)

This issue does not seem to arise on Mac.

Properties v0.3.5 (from pip install)
Discretize from dev branch

Thanks!

**Comment by thast** [comment]
This error disappears when being on the Master branch for Discretize.
I am able to run it on my Windows Machine.

**Comment by lheagy** [comment]
@thast: Have you updated your properties? pip install --upgrade properties

**Comment by thast** [comment]
@lheagy : Thanks! Indeed, `pip install --upgrade properties` was still importing `properties 0.3.5`. That's why I thought we were up to date. 
The command I had to run to get 0.3.6b0 was ` pip install --pre properties --upgrade` (only `--upgrade` or `--pre` still get me the 0.3.5)
So `discretize` and `SimPEG` works on my Windows 10 machine! I will link this issue with the one about Windows on SimPEG, just in case.
