### ISSUE TITLE
possible bug in tree mesh readmodelUBC

### ISSUE THREAD

**Issue by craigmillernz** [simpeg/discretize#99]
when reading in a octree model using `mesh = Mesh.TreeMesh.readUBC(mesh_file)` and then the model using `model = mesh.readModelUBC(model_file)` it appears that the model is returned as a list of an array,  model
Out[62]: 
[array([ 3.28385e-03,  3.40776e-03,  5.75453e-03, ..., -9.99900e+03,
       -9.99900e+03, -9.99900e+03])]

note extra brackets at start and end.
when reading a tensor model it just returns an array
with no extra brackets

**Comment by jcapriot** [comment]
Do not know why it was doing this, the original implementation did this so the accel branch did it too.
I've updated it to simply return the numpy array now #94
